### ISSUE TITLE
stress_test.py data elements may have changed

### ISSUE THREAD

**Issue by jmcsagdc** [obi-wan-shinobi/Stress-test#1]
I'm probably doing it wrong, but when I first ran it, I got an error saying something along the lines of 'expected 5 values, got more'. I literally just copied the one script and ran it, so probably missed a setup step or something.

After a quick debug print, it looks like the problem was at line 117:

def pmem():
    '''
    Function to display memory statistics
    '''
    print(psutil.virtual_memory()).              # <-------debug
    print("tot, avail, percent, used, free")  # <-------debug
    tot, avail, percent, used, free ,_ ,_ ,_ ,_ ,_ ,_ = psutil.virtual_memory()  # <- added 6 ,_ to align values (yes, messy)

Here's my output when I added the list comprehension throw-aways:

PU and Memory Stress in progress:
svmem(total=4140290048, available=3447537664, percent=16.7, used=480227328, free=3482546176, active=367611904, inactive=147927040, buffers=3563520, cached=173953024, shared=5607424, slab=56397824)
tot, avail, percent, used, free
---------------------------------------
Memory Stats: total = 3.855945587158203 GB 
avail = 3.2107696533203125 GB 
used = 0.4472465515136719 GB 
free = 3.2433738708496094 GB 
percent = 16.7
Killed

**Comment by obi-wan-shinobi** [comment]
I'll look into it :)

**Comment by obi-wan-shinobi** [comment]
I'm afraid the data elements are specific to a UNIX like operating system but not to Windows. It'd be useful if you created a PR that fixes the issue a bit more efficiently than the current solution. Thanks for bringing this to attention. Any help is appreciated :)
